<template>
    <article class="edenPageContent">
								<h1 class="entry-title">Becoming A Christian</h1><div id="post-59" class="article post-59 page type-page status-publish hentry"><p>If you’re serious about becoming a Christian, there are a few things you need to understand.</p>
<p>Becoming a Christian is not like joining a club, neither is it the same as taking up a new interest or hobby. Your desire to be a Christian has to come from a sense of overwhelming need, and such a sense can’t be created by a casual interest, but only by God working in your heart and mind.</p>
<p>You can’t make yourself a Christian. You can decide to call yourself a Christian, but that’s not the same as being one. This is true because of what a Christian is. By definition, a Christian is a Christ-person, one who loves the Lord Jesus Christ and seeks to live his or her life according to the Saviour’s teaching. But this is contrary to all that we are by nature, so that nature first has to be changed if we are to be Christians, and only God can do that.</p>
<p>This shows us that only God can make us Christians. That’s why the apostle Paul in Ephesians 2:10 describes himself and other believers by saying, ‘We are God’s workmanship.’ Each Christian is the product of an extraordinary work of Almighty God.</p>
<p>Does this mean then that there is nothing we can do to become Christians, and that we must just wait for God to work in us? It’s true that there’s nothing we can do to save ourselves, but the Bible does tell us to seek the Lord.</p>
<h3>What can we say, then?</h3>
<p><strong>We need to be Christians because our sin separates us from God</strong> and will eventually take us to hell. Sin, guilt and judgment are truths that we may not like, but they are the only explanations for the state of the world today and for the state of our hearts. These are the reasons why we need to become Christians.</p>
<p><strong>If we are to be Christians it must be by God’s way</strong>,and God has only one way: this is through his Son, the Lord Jesus Christ. Christ is not one of many ways to God; he is the only way. That’s not bigotry or intolerance; it’s simply the truth.</p>
<p><strong>When Jesus died on the cross, he did so to fulfill God’s plan of salvation for sinners</strong>. God made Jesus responsible for our sin, and Jesus gladly accepted that awful responsibility. So when he died on the cross, he did so as a sacrifice, bearing our sin and guilt, and taking the punishment for that sin. He died in our place. In this way God satisfied his own holiness, in that sin was dealt with legally and justly, and at the same time he is now able to forgive guilty sinners from all their sin.</p>
<p><strong>To ‘seek the Lord’ means that we acknowledge our own sin and guilt</strong>, and plead with God to save us from its consequence. This he can and will do because of what the Lord Jesus did on the cross.</p>
<p><strong>God makes us Christians not only by forgiving our sin but also by dealing with the root of our problem.</strong> This is not our sinful behaviour but our sinful nature, which dictates our actions. He changes our nature by giving us new desires, new longings, new ambitions and new attitudes. This is done by the power of his Holy Spirit, which becomes the motivating force in our lives. When someone becomes a Christian, he or she is a new person. Christ now rules and reigns in his or her heart.</p>
<p><strong>If you believe these things and you really want to become a Christian, then there is only one thing to do.</strong> Trust in Christ alone to save you, and hate your own sin. Plead with God to have mercy on you. Do this until you know God’s peace in your heart. When you seek the Lord like this, you can be sure that he will not turn you away.</p>
<p><em>Peter Jeffery<br />
</em><em>© Day One Publications,</em><em> </em>
<a href="https://www.dayone.co.uk/"><em>www.dayone.co.uk</em></a></p>
</div>							</article>
</template>